<?php

$lang = array(
		//BUTTONS
		'SAVE_CHANGES' => 'Save',
		'CANCEL_CHANGES' => 'Cancel',

		//TABLE
		"SAVED_CHANGES" => 'Your changes has been saved',
		'TABLE_ACTIONS' => 'Actions',
		'TABLE_EDIT' => 'Edit',
		'TABLE_DELETE' => 'Delete',
		'TABLE_ROWS' => 'Rows',
		'TABLE_UP' => 'Move Up',
		'TABLE_DOWN' => 'Move Down',
		'CROP' => 'Crop',
		'CROP_IMAGE' => 'Crop Image',
		'DRAG_DROP_INFO' => 'Drag and Drop images into the content or use the following input',
		
		//MENU
		'MENU_DASHBOARD' => 'Dashboard',
		'MENU_OTHERS' => 'Others',
		'MENU_META_TAGS' => 'Meta Tags',
		'MENU_VARIABLES' => 'Variables',
		'MENU_USERS' => 'Administrators',
		
		//LOGIN
		'LOGIN_INFO' => 'Enter username and password to continue.',
		'LOGIN_HELLO' => 'Hello',
		'LOGIN_USERNAME' => 'Username',
		'LOGIN_PASSWORD' => 'Password',
		'LOGIN_LOST_PASSWORD' => 'Lost password?',
		'LOGIN_LOGIN' => 'Login',
		'LOGIN_LOST_INFO' => 'Enter your e-mail address below and we will send you instructions how to recover a password.',
		'LOGIN_LOST_EMAIL' => 'E-mail address',
		'LOGIN_LOST_LOGIN' => 'Click to login',
		'LOGIN_LOST_RECOVER' => 'Recover',
		'LOGIN_RECOVER_SUBJECT' => 'Password Change',
		'LOGIN_RECOVER_MSG' => 'Your new password is: ',
		'LOGIN_RECOVER_SUCCESS' => 'Your new password will be sent to your email',
		
		//HEADER
		'HEADER_LOGOUT' => 'Logout',
		'HEADER_DASHBOARD' => 'Dashboard',
		
		//HOME
		'HOME_BREADCRUM' => 'Go to Home',
		'HOME_HOME' => 'Home',
		
		//META TAGS
		"META_TAGS_TITLE" => 'Meta Tags',
		"META_TAGS_SAVED" => 'Meta tags saved',
		"META_TAGS_DESCRIPTION" => 'Description',
		"META_TAGS_KEYWORDS" => 'Keywords',
		"META_TAGS_AUTHOR" => 'Author',
		
		//SYSTEM VARIABLES
		'SYSTEM_TITLE' => 'System Variables',
		'SYSTEM_ADMIN_TITLE' => 'Admin Variables',
		'SYSTEM_ADMIN_LANGUAGE' => 'Language',
		'SYSTEM_FRONT_TITLE' => 'Front Variables',
		'SYSTEM_IMAGES' => 'Images',
		'SYSTEM_FAVICON' => 'Favicon',
		'SYSTEM_PAGE_NAME' => 'Page Name',
		'SYSTEM_LOGO' => 'Logo',
		'SYSTEM_NO_REPLY_EMAIL' => 'No Reply Email',
		'SYSTEM_COMMON_VARIABLES' => 'Common Variables',
		'SYSTEM_FRONT_LANGUAGE' => 'Site Language',
		'SYSTEM_DATETIME_FORMAT' => 'Datetime Format',
		'SYSTEM_EXAMPLES_LINK' => 'Example',
		'SYSTEM_DATE_FORMAT' => 'Date Format',
		'SYSTEM_SAVED' => 'Variables saved successfully',
		
		//ADMIN USERS
		"HEADER_ADMIN_USERS" => 'Admin Users',
		"ADMIN_NEW_USER" => 'New User',
		"ADMIN_EDIT_USER" => 'Edit User',
		"ADMIN_LIST_USER" => 'Admin Users',
		"ADMIN_NOT_FOUND" => 'Error: User not found.',
		"ADMIN_DELETED" => 'User deleted',
		"ADMIN_PASSWORD" => 'Password',
		"ADMIN_EMAIL" => 'Email',
		"ADMIN_INFO" => 'User Information',
		"ADMIN_CHANGE_PASSWORD" => 'Change Password',
		"ADMIN_TABLE_USER" => 'User',
		"ADMIN_TABLE_EMAIL" => 'Email',
		"ADMIN_ADD_USER" => 'Add User',
		"ADMIN_DELETE_USER_CONFIRM" => 'Do you want to delete this user?',
		
		"ADMIN_ERROR_1" => 'Username could not be null',
		"ADMIN_ERROR_2" => 'Wrong Password',
		"ADMIN_ERROR_3" => 'Wrong Email',
		"ADMIN_ERROR_4" => 'Username already exists',		
);

?>